language: csharp
solution: WebApiCoreSeed.sln
os: linux
dotnet: "2.0.0"
mono: none
install: dotnet restore
script:
  - dotnet build --configuration release
  - dotnet test WebApiCoreSeed.Domain.Tests/WebApiCoreSeed.Domain.Tests.csproj --configuration release
  - dotnet test WebApiCoreSeed.Infrastructure.Tests/WebApiCoreSeed.Infrastructure.Tests.csproj --configuration release